### ISSUE TITLE
I can't see the file obj.csv

### ISSUE THREAD

**Issue by JoeLambourne** [cluster3d/cluster3d.github.io#1]
This dataset looks amazing!   This is just what we need to move B-Rep research on to the next level.

I can't see the obj.csv file anywhere.  Is it not available yet?

Also is there any further documentation.   I'm wondering how the labels for the edges work.  Are they based on the STEP or Parasolid edge indices, or on 3D points on the edges.

**Comment by siyuan2018** [comment]
Hi Joe, thanks for your interest in our work!  

The Github page is still under construction, but all the data is available on our Google Drive now! Please see that in Readme. Specifically, we are using CAD models from ABC dataset, so in obj.csv file, we only recorded the indices of the data that we used.  

Also, by saying edge, we are not talking about edge in terms of geometry definition. Instead, we define "edge" as the similarity relationship between each two CAD models. Say model A is similar as model B, then we define the edge between them as 1.

Hope this clarifies, thanks!

**Comment by JoeLambourne** [comment]
Thank you @siyuan2018.   That's great!
I've just got some code working which starts to plot the clusters and lets me understand the data.

Thank you for your help with this
